typography_spectrum: 0.4197450957726687
color:
  brandStrength: 0.9147257392760366
  lightness: 0.49233408411964774
  saturation: 0.8683215982746333
  rhythmicContrast: 0.8846447360701859
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
layout_spectrum: 0.08981988439336419
author:
  name: Chad Moeller
  email: chad@grey-raven.com
  url: 'http://www.grey-raven.com'
name: Grey-Raven Mercantile
title: >-
  Rugged primitive furniture and accessories with unexpected refinement. Made in
  Maine by hand.
description: Responsible. Rugged. Refined.
